baseURL = 'http://michaelborgmann.github.io/zenai'
languageCode = 'en-us'
title = 'ZenAI'
theme = 'simple'

[caches]
  [caches.images]
    dir = ':cacheDir/images'
    
[menus]
  [[menus.main]]
    name = 'ZenAI'
    url = '/'
    weight = 10
  [[menus.main]]
    name = 'About'
    url = 'about'
    weight = 20
  [[menus.main]]
    name = 'Blog'
    url = 'blog'
    weight = 30
  [[menus.main]]
    name = 'News'
    url = 'news'
    weight = 40
  [[menus.main]]
    name = 'AI'
    url = 'ai-technologies'
    weight = 50